routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/agenda', 'AgendaController');

Route::get('/agenda/{assunto}/delete', 'AgendaController@destroy')->name('agenda.destroy');

Route::get('/sobre', function(){
    return view('sobre');
});

app/Models/Assunto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Assunto extends Model
{

    protected $primaryKey = "id";

    protected $fillable = [
    'cadeira', 'assunto', 'data', 'descricao', 'data'
    ];

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AgendaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Assunto;

class AgendaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $assuntos = Assunto::all();
        return view('agenda.index')->with(['assuntos' => $assuntos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('agenda.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Assunto::create($request->all());

        return redirect()->route('agenda.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $assunto = Assunto::find($id);
        return view('agenda.show')->with(['assunto' => $assunto]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $assunto = Assunto::find($id);
        return view('agenda.edit')->with(['assunto' => $assunto]);;
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $assunto = Assunto::find($id)->update($request->all());
        return redirect()->route('agenda.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $assunto = Assunto::find($id)->delete();
        return redirect()->route('agenda.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/disciplinaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class disciplinaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/agenda/create.blade.php
@include('agenda.navbar')
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
    crossorigin="anonymous">
</head>
<body>
    <center><h1>Adicionar atividade</h1></center>
    <br>
    <form action="{{route('agenda.store')}}" method='POST'>
    @csrf
        <center><div class='container'>
            <div class="col-md-12">
                <div class="col-md-6">
                    <label>Cadeira/Disciplina</label>
                    <input type="text" class="form-control" placeholder="Cadeira/Disciplina" name='cadeira'>
                </div>
                <div class="col-md-6">
                    <label>Assunto</label>
                    <input type="text" class="form-control" id="validationTooltip02" placeholder="Assunto" name='assunto'>
                </div>
            </div>
        </div>
            <div class="container">
                <div class='col-md-12'>
                    <div class="col-md-6">
                        <label>Data de entrega</label>
                        <input type="date" class="form-control" id="validationTooltip03" placeholder="Data" name='data'>
                    </div>
                    <div class="col-md-6">
                        <label>Descrição</label>
                        <input type="text" class="form-control" id="validationTooltip04" placeholder="Descrição" name='descricao'>
                    </div>
                </div>
            </div>
            <br>
            
            <button class="btn btn-success" type="submit">Criar</button>
            <button class="btn btn-outline-primary" style="width:5%"><a href="{{ route('agenda.index')}}">Voltar<a/></button>
            </form>
        </div></center>
    </form>
</body>
</html>

resources/views/agenda/edit.blade.php
@include('agenda.navbar')
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    


<center><h1>Editar o {{ $assunto->cadeira }}</h1></center>
    <form action="{{route('agenda.update', [ $assunto->id ])}}" method='POST'>
    @csrf
    @method('PUT')
        <center><div class='container'>
            <div class="col-md-12">
                <div class="col-md-6">
                    <label>Cadeira/Disciplina</label>
                    <input type="text" class="form-control" placeholder="Cadeira/Disciplina" name='cadeira' value="{{ old('cadeira', $assunto->cadeira) }}">
                </div>
                <div class="col-md-6">
                    <label>Assunto</label>
                    <input type="text" class="form-control" id="validationTooltip02" placeholder="Assunto" name='assunto' value="{{ old('cadeira', $assunto->assunto) }}">
                </div>
            </div>
        </div>
            <div class="container">
                <div class='col-md-12'>
                    <div class="col-md-6">
                        <label>Data de entrega</label>
                        <input type="date" class="form-control" id="validationTooltip03" placeholder="Data" name='data' value="{{ old('cadeira', $assunto->data) }}">
                    </div>
                    <div class="col-md-6">
                        <label>Descrição</label>
                        <input type="text" class="form-control" id="validationTooltip04" placeholder="Descrição" name='descricao' value="{{ old('cadeira', $assunto->descricao) }}">
                    </div>
                </div>
            </div>
            <br>
            <button class="btn btn-success" type="submit">Atualizar</button>
            <button class="btn btn-outline-primary" style="width:5%"><a href="{{ route('agenda.index')}}">Voltar<a/></button>
            </form>
        </div></center>
    </form>




</body>
</html>

resources/views/agenda/index.blade.php
@include('agenda.navbar')
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <META http-equiv="Page-Enter" CONTENT="RevealTrans(Duration=2,Transition=4)">
</head>
<body>
    <center><h1>Atividades</h1></center>
    <br>
    <center><div style="width:900px;">
    <table class="table table-borderless">
        <thead>
            <tr >
            <th scope="col">Disciplina</th>
            <th scope="col">Assunto</th>
            <th scope='col'>Opções</th>
            </tr>
        </thead>
        <tbody>
        @foreach($assuntos as $assunto)
            <tr>
                <td>{{$assunto -> cadeira}}</td>
                <td>{{$assunto -> assunto}}</td>
                <td>
                <a href="{{ route('agenda.show', [$assunto->id]) }}">
                    <svg class="bi bi-eye" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.134 13.134 0 001.66 2.043C4.12 11.332 5.88 12.5 8 12.5c2.12 0 3.879-1.168 5.168-2.457A13.134 13.134 0 0014.828 8a13.133 13.133 0 00-1.66-2.043C11.879 4.668 10.119 3.5 8 3.5c-2.12 0-3.879 1.168-5.168 2.457A13.133 13.133 0 001.172 8z" clip-rule="evenodd"/>
                        <path fill-rule="evenodd" d="M8 5.5a2.5 2.5 0 100 5 2.5 2.5 0 000-5zM4.5 8a3.5 3.5 0 117 0 3.5 3.5 0 01-7 0z" clip-rule="evenodd"/>
                    </svg>
                </a>
                <a href="{{ route('agenda.edit', [$assunto->id]) }}">
                    <svg class="bi bi-pencil" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M11.293 1.293a1 1 0 011.414 0l2 2a1 1 0 010 1.414l-9 9a1 1 0 01-.39.242l-3 1a1 1 0 01-1.266-1.265l1-3a1 1 0 01.242-.391l9-9zM12 2l2 2-9 9-3 1 1-3 9-9z" clip-rule="evenodd"/>
                        <path fill-rule="evenodd" d="M12.146 6.354l-2.5-2.5.708-.708 2.5 2.5-.707.708zM3 10v.5a.5.5 0 00.5.5H4v.5a.5.5 0 00.5.5H5v.5a.5.5 0 00.5.5H6v-1.5a.5.5 0 00-.5-.5H5v-.5a.5.5 0 00-.5-.5H3z" clip-rule="evenodd"/>
                    </svg>
                </a>
                <a href="{{ route('agenda.destroy', [$assunto->id]) }}">
                    <svg class="bi bi-trash" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M5.5 5.5A.5.5 0 016 6v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm2.5 0a.5.5 0 01.5.5v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm3 .5a.5.5 0 00-1 0v6a.5.5 0 001 0V6z"/>
                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 01-1 1H13v9a2 2 0 01-2 2H5a2 2 0 01-2-2V4h-.5a1 1 0 01-1-1V2a1 1 0 011-1H6a1 1 0 011-1h2a1 1 0 011 1h3.5a1 1 0 011 1v1zM4.118 4L4 4.059V13a1 1 0 001 1h6a1 1 0 001-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" clip-rule="evenodd"/>
                    </svg>
                </a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    </div></center>
</body>
</html>

resources/views/agenda/navbar.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agenda</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
    crossorigin="anonymous">
</head>
<body>


<ul class="nav justify-content-end">
  <li class='nav-link active'>
    Agenda
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="/">Inicio</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="{{ route('agenda.index')}}">Lista de atividades</a>
  </li>
  <li>
    <a class="nav-link active" href="{{ route('agenda.create')}}">
      <svg class="bi bi-plus-square" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M8 3.5a.5.5 0 01.5.5v4a.5.5 0 01-.5.5H4a.5.5 0 010-1h3.5V4a.5.5 0 01.5-.5z" clip-rule="evenodd"/>
        <path fill-rule="evenodd" d="M7.5 8a.5.5 0 01.5-.5h4a.5.5 0 010 1H8.5V12a.5.5 0 01-1 0V8z" clip-rule="evenodd"/>
        <path fill-rule="evenodd" d="M14 1H2a1 1 0 00-1 1v12a1 1 0 001 1h12a1 1 0 001-1V2a1 1 0 00-1-1zM2 0a2 2 0 00-2 2v12a2 2 0 002 2h12a2 2 0 002-2V2a2 2 0 00-2-2H2z" clip-rule="evenodd"/>
      </svg>
    </a>
  </li>
</ul>

</body>
</html>

resources/views/agenda/show.blade.php
@include('agenda.navbar')
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalhe</title>
</head>
<body>
    <center><h3>Detalhamento do {{$assunto->cadeira}}</h3>
    <br>
        <div style="width:900px;">
        <table>
            <tr>
                <h5>Cadeira</h5>
                <a class="list-group-item list-group-item-action list-group-item-primary">{{$assunto->cadeira}}</a>
                <h5>Assunto</h5>
                <a class="list-group-item list-group-item-action list-group-item-primary">{{$assunto->assunto}}</a>
                <h5>Data de entrega</h5>
                <a class="list-group-item list-group-item-action list-group-item-primary">{{$assunto->data}}</a>
                <h5>Descrição</h5>
                <a class="list-group-item list-group-item-action list-group-item-primary">{{$assunto->descricao}}</a>
            </tr>
        </table>
        </div>
    <br>
    <button class="btn btn-outline-primary" style="width:5%"><a href='{{ route('agenda.index')}}'>Voltar</a></button>
    </center>
</body>
</html>

resources/views/sobre.blade.php
@include('agenda.navbar')
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="<?php echo asset('css/inicio.css')?>" type='text/css' >
</head>
<body>

    <center><h1>Sobre o sistema</h1></center>
    <br>
    <h4>Backend</h3>
    <p>
        Foi desenvolvivo na linguagem PHP <img src="https://img.icons8.com/color/48/000000/php.png"/ width=2%>
    </p>
    <p>
        Usando-se o Framework Laravel <img src="imagens/laravel.png" width=3%>
    </p>
    <br>
    <h4>Frontend</h4>
    <p>
        Foi usando Bootstrap <img src="imagens/bootstrap.png" width=3%>
    </p>
    <br>
    <h4>Banco de dados</h4>
    <p>
        Foi usando o banco de dados oferecido pelo próprio PHP, o PhpMyAdmin <img src='imagens/banco.png' width=5%>
    </p>

    <center><h1>Sobre o criador</h1></center>
    <br>
    <h4>Pessoal</h4>
    <p>
        Olá, sou Pedro Henrique da Silva Pontes, tenho 20 anos, moro na cidade de Sapé, interior da Paraíba.<p>
        E-mail para contato: pedrohenriquedasilv@gmail.com
    </p>
    <h4>Acadêmico</h4>
    <p>
        Atualmente, 04/05/2000, estou cursando Sistemas Para Internet P4, no centro Universitário de João Pessoa.<p>
        Ja atuei na Fábrica de Software, um grupo de equipes dentro da própria UNIPÊ, com objetivo de desenvolver
        sistemas para empresas de João Pessoa e para a própria UNIPÊ.
        <p>Nesse periodo participei da equipe que desenvolveu o projeto "Contrapartida", é um sistema de gerenciamento
        de parcerias de estágio feita entre a UNIPÊ e empresas de JP.
    </p>
    <h5>Conhecimentos</h5>
    <p class='conhecimentos'>
        Linguagens já trabalhadas: Python e PHP
    </p>
    <p class='conhecimentos'>
        Frameworks já trabalhados: Django e Laravel
    </p>
    <p class='conhecimentos'>
        Conhecimento básico de Banco Mysql
    </p>
</body>
</html>